version: '3'

tasks:
  api: 
   cmds:
     - goctl api go -api greet.api -dir .
  load:
    cmds:
      - kind load docker-image api-greet:v1.0.1 --name kind-test
  deploy:
    cmds:
      - kubectl apply -f deploy.yaml
  shell:
    cmds:
      - docker exec -it kind-test-control-plane /bin/bash