apiVersion: v1
kind: Namespace
metadata:
  name: grpc-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grpc-user
  name: grpc-user
  labels:
    app: grpc-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-user
  template:
    metadata:
      labels:
        app: grpc-user
    spec:
      containers:
        - name: grpc-user
          image: grpc-user:v1.0.1
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: grpc-user
  name: grpc-user-service
spec:
  selector:
    app: grpc-user
  ports:
  - protocol: TCP
    port: 8080      
    targetPort: 8080
  type: ClusterIP   
