apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rpc-user
  name: rpc-user
  labels:
    app: rpc-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpc-user
  template:
    metadata:
      labels:
        app: rpc-user
    spec:
      containers:
        - name: rpc-user
          image: fengyuxiu/zero-greeet-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: rpc-user
  name: rpc-user-service
spec:
  selector:
    app: rpc-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
