apiVersion: v1
kind: Namespace
metadata:
  name: grpc-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grpc-user
  name: rpc-user
  labels:
    app: rpc-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpc-user
  template:
    metadata:
      labels:
        app: rpc-user
    spec:
      containers:
        - name: rpc-user
          image: fengyuxiu/zero-greet-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: grpc-user
  name: grpc-user-service
spec:
  selector:
    app: rpc-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
