version: '3'

tasks:
  rpc: 
   cmds:
     - goctl --version
     - goctl rpc protoc user.proto --go_out=. --go-grpc_out=. --zrpc_out=.
  load:
    cmds:
      - kind load docker-image rpc-user:v1.0.0 --name istio-cluster
  deploy:
    cmds:
      - kubectl apply -f deploy.yaml